# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02377d6baf1df3f65fd6f3c0691299bff4fb78b69e066e60e7cde0e5584b6ef965704c597414ead54f0069fa8ebcce9b2a587c14206de425a15a60412e4e9301

test:
  secret_key_base: 2731a019b8948d4f8febe2b8bf5ebf0585959a8d590964e5a80ac435bc51bddcb4d0a4234f0eecd8eaa2c80a3bafc77fe73ca6689c827bf1afaf8b1ea0d11e6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
